### ISSUE TITLE
Curves Being Choped and Some Suggestions

### ISSUE THREAD

**Issue by BhanteDhamma** [Darakah/obsidian-gallery#2]
Great idea for a plugin.

I noticed the curves of the image display are being chopped, maybe if they are zoomed in, could be a choice for curves on all corners?
![lions-pose](https://user-images.githubusercontent.com/76240934/111023995-37c98500-8417-11eb-8186-917afb2348da.png)

Even better some other suggestions
- Option to show full image, or provide css for how to change the layout.
- A great idea would be to make the image clickable (within the obsidan vault would be great, just like when you normally click on an image in the vault and it opens on its own).
- 
At the moment the images are only paritally showing, I only have a 700 width panel, and editing the css manually dosn't seem to help.

Anyway I am no css pro. Good idea though, thanks :-)

**Comment by theSiberman** [comment]
Clickable images would be fantastic!

Great plugin!

**Comment by Darakah** [comment]
Fixed in version `0.5.0`

**Added Grid View:**
----
- Added **new view** for display which **shows full images** (contain and not fit) using view `type=grid`
- Added the ability to open images by `right-click` 
- Ability to specific the width of the images through command block arguments

Options not added for old view (`type=active-thumb`) for now.

**Border-radius:**
----
- Moved `active-thumb` type view css from svelte component to `style.css`
- Can change the border cropping by changing this line @BhanteDhamma `border-radius: 10px 10px 10px 10px;` found inside the style.css file now in the block:

```css
/* active-thumb View CSS */

.gallery-widget {
    background: var(--background-secondary);
    height: 100%;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    padding-bottom: 60%;
    background-size: cover;
    background-position: center center;
    border-radius: 10px 10px 10px 10px;
}

.gallery-container {
    max-width: auto;
    width: auto;
}
```

simply change the `10` to `0` to remove the cropping or larger to increase the cropping on each of the 4 corners, previously set to `border-radius: 10px 10px 0px 0px;`
